# Python Bootcamp: Advent of Code (Day X)

## 1. Puzzle 1

### 1.1 My Solution

In [127]:
def get_part1_answer(data):

    # Select only line segments which are horizontal or vertical
    x1_list = []
    x2_list = []
    y1_list = []
    y2_list = []

    for ele in data:
        x1 = ele.split(' -> ')[0].split(',')[0] 
        y1 = ele.split(' -> ')[0].split(',')[1] 
        x2 = ele.split(' -> ')[1].split(',')[0] 
        y2 = ele.split(' -> ')[1].split(',')[1]

        if (x1 == x2) or (y1 == y2):
            x1_list.append(int(x1))
            x2_list.append(int(x2))
            y1_list.append(int(y1))
            y2_list.append(int(y2))

        else:
            pass

    # Find the maximum for x and y coordinates
    x_max = max([max(x1_list), max(x2_list)])
    y_max = max([max(y1_list), max(y2_list)])

    # Initialise an empty matrix
    matrix = np.zeros(shape=(x_max+1, y_max+1))

    # Fill the matrix
    for idx in range(len(x1_list)):
        x1 = x1_list[idx]
        x2 = x2_list[idx]
        y1 = y1_list[idx]
        y2 = y2_list[idx]

        if (y1 == y2) & (x1 < x2):
            matrix[y1, x1:x2+1] += 1

        elif (y1 == y2) & (x1 > x2):
            matrix[y1, x2:x1+1] += 1

        elif (x1 == x2) & (y1 < y2):
            matrix[y1:y2+1, x1] += 1

        elif (x1 == x2) & (y1 > y2):
            matrix[y2:y1+1, x1] += 1

    # Return the number of cells with at least 2 overlapping points
    return np.count_nonzero(matrix >= 2)

In [135]:
example_lines = [
    '0,9 -> 5,9\n',
    '8,0 -> 0,8\n',
    '9,4 -> 3,4\n',
    '2,2 -> 2,1\n',
    '7,0 -> 7,4\n',
    '6,4 -> 2,0\n',
    '0,9 -> 2,9\n',
    '3,4 -> 1,4\n',
    '0,0 -> 8,8\n',
    '5,5 -> 8,2\n'
]

example_data = [ele.rstrip('\n') for ele in example_lines]
example_answer = get_part1_answer(example_data)
print(f"Number of points where at least 2 points overlap: {example_answer}")

Number of points where at least 2 points overlap: 5


In [136]:
# Read input file
with open('data/input.txt') as f:
    lines = f.readlines()

data = [ele.rstrip('\n') for ele in lines]
answer = get_part1_answer(data)
print(f"Number of points where at least 2 points overlap: {answer}")

Number of points where at least 2 points overlap: 7436


## 2. Puzzle 2

### 2.1 My Solution

In [199]:
def get_diagonal_points(x1, x2, y1, y2):
    
    if (x1 < x2) & (y1 < y2):
        return list(zip(list(range(x1, x2+1)), list(range(y1, y2+1))))
        
    elif (x1 < x2) & (y1 > y2):
        return list(zip(list(range(x1, x2+1)), list(range(y1, y2-1, -1))))
        
    elif (x1 > x2) & (y1 < y2):
        return list(zip(list(range(x1, x2-1, -1)), list(range(y1, y2+1))))
        
    elif (x1 > x2) & (y1 > y2):
        return list(zip(list(range(x1, x2-1, -1)), list(range(y1, y2-1, -1))))

In [207]:
def get_part2_answer(data):

    # Select only line segments which are horizontal or vertical
    x1_list = []
    x2_list = []
    y1_list = []
    y2_list = []

    for ele in data:
        x1 = ele.split(' -> ')[0].split(',')[0] 
        y1 = ele.split(' -> ')[0].split(',')[1] 
        x2 = ele.split(' -> ')[1].split(',')[0] 
        y2 = ele.split(' -> ')[1].split(',')[1]

        x1_list.append(int(x1))
        x2_list.append(int(x2))
        y1_list.append(int(y1))
        y2_list.append(int(y2))


    # Find the maximum for x and y coordinates
    x_max = max([max(x1_list), max(x2_list)])
    y_max = max([max(y1_list), max(y2_list)])

#     print(x1_list)
#     print(x2_list)
#     print(y1_list)
#     print(y2_list)
    
    # Initialise an empty matrix
    matrix = np.zeros(shape=(x_max+1, y_max+1))

    # Fill the matrix
    for idx in range(len(x1_list)):
        x1 = x1_list[idx]
        x2 = x2_list[idx]
        y1 = y1_list[idx]
        y2 = y2_list[idx]
        print(f"x1 = {x1}; x2 = {x2}")
        print(f"y1 = {y1}; y2 = {y2}")
        
        if (y1 == y2) & (x1 < x2):
            matrix[y1, x1:x2+1] += 1
            print(matrix)

        elif (y1 == y2) & (x1 > x2):
            matrix[y1, x2:x1+1] += 1
            print(matrix)

        elif (x1 == x2) & (y1 < y2):
            matrix[y1:y2+1, x1] += 1
            print(matrix)

        elif (x1 == x2) & (y1 > y2):
            matrix[y2:y1+1, x1] += 1
            print(matrix)
        
        else:
            diagonal_points = get_diagonal_points(x1, x2, y1, y2)
            for x, y in diagonal_points:
                matrix[y, x] += 1
            print(matrix)
        print()
        
    # Return the number of cells with at least 2 overlapping points
    return np.count_nonzero(matrix >= 2)

example_lines = [
    '0,9 -> 5,9\n',
    '8,0 -> 0,8\n',
    '9,4 -> 3,4\n',
    '2,2 -> 2,1\n',
    '7,0 -> 7,4\n',
    '6,4 -> 2,0\n',
    '0,9 -> 2,9\n',
    '3,4 -> 1,4\n',
    '0,0 -> 8,8\n',
    '5,5 -> 8,2\n'
]

example_data = [ele.rstrip('\n') for ele in example_lines]
example_answer = get_part2_answer(example_data)
print(f"Number of points where at least 2 points overlap: {example_answer}")

x1 = 0; x2 = 5
y1 = 9; y2 = 9
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]]

x1 = 8; x2 = 0
y1 = 0; y2 = 8
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]]

x1 = 9; x2 = 3
y1 = 4; y2 = 4
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0

In [208]:
# Read input file
with open('data/input.txt') as f:
    lines = f.readlines()

data = [ele.rstrip('\n') for ele in lines]
answer = get_part2_answer(data)
print(f"Number of points where at least 2 points overlap: {answer}")

x1 = 409; x2 = 409
y1 = 872; y2 = 963
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 149; x2 = 281
y1 = 412; y2 = 280
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 435; x2 = 435
y1 = 281; y2 = 362
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 52; x2 = 969
y1 = 208; y2 = 208
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 427; x2 = 884
y1 = 265; y2 = 265
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 779; x2 = 779
y1 = 74

 [0. 0. 0. ... 0. 0. 0.]]

x1 = 662; x2 = 168
y1 = 874; y2 = 874
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 336; x2 = 336
y1 = 98; y2 = 842
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 289; x2 = 811
y1 = 69; y2 = 591
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 824; x2 = 256
y1 = 777; y2 = 209
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 374; x2 = 374
y1 = 311; y2 = 905
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]



y1 = 750; y2 = 26
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 622; x2 = 488
y1 = 840; y2 = 706
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 909; x2 = 794
y1 = 201; y2 = 201
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 959; x2 = 579
y1 = 185; y2 = 565
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 848; x2 = 848
y1 = 720; y2 = 322
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 81; x2 = 81
y1 = 159; y2 = 652
[[0. 0. 0


x1 = 836; x2 = 668
y1 = 606; y2 = 774
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 557; x2 = 422
y1 = 918; y2 = 918
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 925; x2 = 875
y1 = 889; y2 = 939
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 14; x2 = 467
y1 = 317; y2 = 770
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 638; x2 = 440
y1 = 312; y2 = 312
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 139; x2 = 212
y1 = 3

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 126; x2 = 725
y1 = 329; y2 = 329
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 182; x2 = 99
y1 = 541; y2 = 541
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 410; x2 = 974
y1 = 709; y2 = 709
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 681; x2 = 687
y1 = 202; y2 = 208
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 495; x2 = 733
y1 = 832; y2 = 594
[[0. 0. 0. ... 0. 0. 0.]
 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 946; x2 = 433
y1 = 338; y2 = 851
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 555; x2 = 531
y1 = 241; y2 = 265
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 336; x2 = 336
y1 = 13; y2 = 48
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 688; x2 = 394
y1 = 880; y2 = 880
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 105; x2 = 823
y1 = 143; y2 = 861
[[0. 0. 0. ... 0. 0. 0.]
 [

x1 = 172; x2 = 633
y1 = 217; y2 = 217
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 159; x2 = 159
y1 = 941; y2 = 569
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 468; x2 = 468
y1 = 72; y2 = 787
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 931; x2 = 36
y1 = 935; y2 = 40
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 114; x2 = 360
y1 = 166; y2 = 412
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

x1 = 539; x2 = 349
y1 = 740;